/* Public resources, session-only practice, and an optional on-device teacher helper. */
(()=>{
 const friends=[['cat','Curious cat','assets/curious-cat.gif','🐈'],['swing','Swing friend','assets/swing-friend.gif','🌳'],['eyes','Silly eyes','assets/watching-eyes.gif','👀'],['snow','Snow friend','assets/snow-friend.webp','⛄'],['pup','Sleepy pup','assets/sleepy-pup.webp','🐶']];
 let friend='cat';try{const saved=localStorage.getItem('pointparty-learning-friend');if(friends.some(f=>f[0]===saved))friend=saved;}catch{}
 let tab='explore',quest=null,worker=null,aiBusy=false,aiTimer=null,aiStatus='',aiResult='',topic='',grade='2',kind='warm-up',draftPrompt='';
 const sources=[['AdaptedMind','Playful math and reading with personalized practice. Subscription/trial terms apply.','https://www.adaptedmind.com/','Math & reading'],['Jigzi','Interactive games, matching, flashcards and holiday learning. Free and paid features.','https://jigzi.org/home/search?q=Rosh+Hashanah','Creative learning'],['Seesaw','Activities, student portfolios and classroom sharing. Free and paid plans.','https://app.seesaw.me/','Classroom activities'],['PhET','Free interactive science and math simulations.','https://phet.colorado.edu/','Science'],['LearnEnglish Kids','Free songs, stories and English games from the British Council.','https://learnenglishkids.britishcouncil.org/','English'],['Toy Theater','Free visual math tools and classroom games.','https://toytheater.com/','Math'],['Scratch','Free creative coding and interactive storytelling.','https://scratch.mit.edu/','Create'],['PBS KIDS','Learning games with familiar characters.','https://pbskids.org/games/','Explore']];
 const aiSources=[['Google AI Studio','Free tier with model-dependent limits; teacher account required.','https://aistudio.google.com/'],['MagicSchool','Free teacher plan with usage limits; optional paid upgrades.','https://www.magicschool.ai/pricing'],['HuggingChat','Open model chat for teacher brainstorming; availability and limits can vary.','https://huggingface.co/chat/']];
 const button=(action,label,extra='')=>`<button type="button" class="btn" data-learning="${action}" ${extra}>${label}</button>`;
 const link=(url,label)=>`<a class="btn" href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
 function buddy(){const f=friends.find(f=>f[0]===friend);return `<div class="learning-friend" aria-hidden="true"><img src="${f[2]}" alt="" width="512" height="313" loading="lazy"><span>${f[3]}</span></div>`;}
 function hero(){return `<section class="learning-hero">${buddy()}<div><small>LEARN · PLAY · DISCOVER</small><h2>Little adventures. Big discoveries.</h2><p>Choose a friend, try a number quest, or find your next classroom activity.</p><label for="learningFriend">Classroom friend</label><select id="learningFriend">${friends.map(f=>`<option value="${f[0]}" ${friend===f[0]?'selected':''}>${f[1]}</option>`).join('')}</select> ${button('motion',document.body.classList.contains('v-paused')?'Resume animation':'Pause animation')}</div></section>`;}
 function explore(){return `<section class="panel"><h2>Find a learning adventure</h2><p>Open a resource, choose an activity for your class, then save its share link in Class materials.</p><div class="material-grid">${sources.map(s=>`<article class="material-card"><small>${s[3]}</small><h3>${s[0]}</h3><p>${s[1]}</p>${link(s[2],'Explore')}</article>`).join('')}</div></section><section class="panel"><h2>A simple classroom routine</h2><div class="learning-routine"><article><b>1 · Wonder</b><p>Start with a question or a short story.</p></article><article><b>2 · Play</b><p>Try a matching game, quiz or number quest together.</p></article><article><b>3 · Share</b><p>Ask students to explain their answer or show what they made.</p></article></div></section>`;}
 function numbers(){if(!quest)return `<section class="panel learning-quest"><h2>Number Quest</h2><p>Practice adding together. Three correct answers earn a star. The next question adapts to your answers, and hints help you learn.</p><p class="note">Whole-class practice · session progress · no grades or reward points are changed.</p>${button('start','Start number quest')}</section>`;const q=quest.q;return `<section class="panel learning-quest"><div class="form">${button('end','Finish quest')}${button('present','Show on screen')}</div><p>Level ${quest.level} · ${quest.correct} correct · ${'⭐'.repeat(Math.min(10,Math.floor(quest.correct/3)))||'Your first star is waiting!'}</p>${buddy()}<h2>${q.a} + ${q.b} = ?</h2><div class="screen-choices">${q.choices.map(c=>button('answer',c,`data-value="${c}" ${quest.answered?'disabled':''}`)).join('')}</div><p class="learning-feedback" role="status">${esc(quest.feedback||'Think, count, then choose.')}</p>${quest.answered?button('next','Next adventure'):button('hint','Show a hint')}</section>`;}
 function ai(){return `<section class="panel"><small>FOR TEACHERS</small><h2>A little help planning your lesson</h2><p>Ask for a warm-up, explanation or discussion question. The optional small AI model runs on this device after a one-time download from Hugging Face. It needs no API key or paid account. This experimental model can give weak answers. Try a short English topic; review every draft before using it in class.</p><form id="teacherHelperForm" class="portal-form"><label for="helperTopic">Lesson topic</label><input id="helperTopic" maxlength="160" required value="${esc(topic)}" placeholder="e.g. plants, addition, kindness"><div class="portal-columns"><div><label for="helperGrade">Grade</label><select id="helperGrade">${[1,2,3,4,5,6].map(g=>`<option ${String(g)===grade?'selected':''}>${g}</option>`).join('')}</select></div><div><label for="helperKind">Help me create</label><select id="helperKind">${[['warm-up','A warm-up'],['explain','A simple explanation'],['question','A discussion question']].map(k=>`<option value="${k[0]}" ${k[0]===kind?'selected':''}>${k[1]}</option>`).join('')}</select></div></div><p class="note">Use lesson topics only. Do not enter student names or private records.</p><div class="form"><button class="btn go" type="submit" ${aiBusy?'disabled':''}>${aiBusy?'Working…':'Create with on-device AI'}</button>${button('prompt','Build a prompt')}${aiBusy?button('cancel-ai','Cancel'):''}</div></form><p role="status" id="helperStatus">${esc(aiStatus)}</p>${aiResult?`<article class="helper-answer"><b>Idea to review</b><p>${esc(aiResult)}</p>${button('copy-answer','Copy idea')}</article>`:''}${draftPrompt?`<article class="helper-answer"><b>Prompt for your preferred AI tool</b><p>${esc(draftPrompt)}</p>${button('copy-prompt','Copy prompt')}</article>`:''}</section><section class="panel"><h2>Free AI starting points</h2><p>These open as separate teacher tools. Free tiers have limits and may change. No class data is sent when you open a link.</p><div class="material-grid">${aiSources.map(s=>`<article class="material-card"><h3>${s[0]}</h3><p>${s[1]}</p>${link(s[2],'Open teacher tool')}</article>`).join('')}</div></section>`;}
 function renderHub(){view.innerHTML=hero()+`<div class="material-tabs">${[['explore','Explore resources'],['numbers','Number Quest'],['ai','Teacher AI helper']].map(t=>button('tab',t[1],`data-tab="${t[0]}" aria-pressed="${tab===t[0]}"`)).join('')}</div>`+(tab==='numbers'?numbers():tab==='ai'?ai():explore());}
 function readPrompt(){topic=$('#helperTopic').value;grade=$('#helperGrade').value;kind=$('#helperKind').value;return LearningCore.teacherPrompt(topic,grade,kind);}
 function finishAI(text,error=false){clearTimeout(aiTimer);aiBusy=false;if(error)aiStatus=text;else if(!LearningCore.answerMatchesTopic(text,topic)){aiResult='';aiStatus='The small model did not give a relevant answer. Use the prepared prompt with a teacher AI tool below.';}else{aiResult=text;aiStatus='Draft ready. Check it for accuracy and suitability.';}if(ui.mode==='learning'&&tab==='ai')renderHub();}
 function createAI(prompt){aiBusy=true;aiResult='';aiStatus='Starting the on-device helper…';renderHub();try{if(!worker){worker=new Worker('teacher-ai-worker.js',{type:'module'});worker.onmessage=({data})=>{if(data.type==='status'){aiStatus=data.text;if(ui.mode==='learning'&&tab==='ai'&&$('#helperStatus'))$('#helperStatus').textContent=aiStatus;}else finishAI(data.text,data.type==='error');};worker.onerror=()=>{worker?.terminate();worker=null;finishAI('The helper could not load. Copy your prompt into a teacher AI tool below.',true);};}worker.postMessage({type:'generate',prompt});aiTimer=setTimeout(()=>{worker?.terminate();worker=null;finishAI('Loading took too long on this device. Try again, or use the prompt with another teacher tool.',true);},240000);}catch{finishAI('Your browser could not start the helper. Use the prompt builder instead.',true);}}
 NAV[0].items.splice(2,0,['learning','🌱','Learning adventures','Games, animated friends and teacher ideas']);PAGES.learning={icon:'🌱',label:'Learning adventures',sub:'Curiosity grows here'};RENDER.learning=renderHub;
 document.addEventListener('change',e=>{if(e.target.id==='learningFriend'){friend=e.target.value;try{localStorage.setItem('pointparty-learning-friend',friend);}catch{}renderHub();}});
 document.addEventListener('submit',e=>{if(e.target.id!=='teacherHelperForm')return;e.preventDefault();if(aiBusy)return;try{draftPrompt=readPrompt();createAI(LearningCore.modelPrompt(topic,kind));}catch(error){toast(error.message);}});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-learning]');if(!b)return;e.preventDefault();const a=b.dataset.learning;
  if(a==='tab'){tab=b.dataset.tab;renderHub();}
  else if(a==='start'){quest={level:1,streak:0,correct:0,q:LearningCore.question(1),feedback:'',answered:false};renderHub();}
  else if(a==='end'){quest=null;renderHub();}
  else if(a==='hint'&&quest){quest.feedback=`Start at ${quest.q.a}, then count ${quest.q.b} more. Try using your fingers or drawing dots.`;renderHub();}
  else if(a==='answer'&&quest&&!quest.answered){const correct=Number(b.dataset.value)===quest.q.answer;quest.answered=true;quest.streak=correct?quest.streak+1:0;quest.correct+=correct?1:0;quest.feedback=correct?'You did it! '+quest.q.a+' + '+quest.q.b+' = '+quest.q.answer:'Good try! '+quest.q.a+' + '+quest.q.b+' = '+quest.q.answer+'. Let’s count together.';quest.level=LearningCore.nextLevel(quest.level,correct,quest.streak);if(quest.streak>=3)quest.streak=0;if(correct)sfx.plus();renderHub();}
  else if(a==='next'&&quest){quest.q=LearningCore.question(quest.level);quest.answered=false;quest.feedback='';renderHub();}
  else if(a==='present'){if(!document.body.classList.contains('present'))togglePresent();}
  else if(a==='motion'){document.body.classList.toggle('v-paused');document.dispatchEvent(new Event('pointparty-motion-change'));renderHub();}
  else if(a==='prompt'){try{draftPrompt=readPrompt();renderHub();}catch(error){toast(error.message);}}
  else if(a==='cancel-ai'){worker?.terminate();worker=null;finishAI('Cancelled. You can try again or use the prompt builder.',true);}
  else if(a==='copy-prompt'||a==='copy-answer'){try{await navigator.clipboard.writeText(a==='copy-prompt'?draftPrompt:aiResult);toast('Copied.');}catch{toast('Select the text and copy it with your keyboard.');}}
 });
})();
