const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
test('school security: invitation, approval, isolation, revocation and concurrent saves',async()=>{
 const db=new PGlite();
 const admin='00000000-0000-0000-0000-000000000001';
 const teacher='00000000-0000-0000-0000-000000000002';
 const outsider='00000000-0000-0000-0000-000000000003';
 try{
  await db.exec(`create role anon; create role authenticated; create schema auth;
   create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);
  await db.exec(fs.readFileSync('supabase/schema.sql','utf8'));
  await db.query('insert into auth.users values ($1,$2,now()),($3,$4,now()),($5,$6,now())',[admin,'admin@example.org',teacher,'teacher@example.org',outsider,'outsider@example.org']);
  await db.query('insert into pp_admins values ($1)',[admin]);
  const as=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
  const rpc=async(sql,args=[])=>await db.query(sql,args);
  await as(admin);
  const a=(await rpc("select pp_create_school('School A') id")).rows[0].id;
  const b=(await rpc("select pp_create_school('School B') id")).rows[0].id;
  assert.equal((await rpc('select * from pp_schools')).rows.length,2);
  await rpc('select pp_invite($1,$2)',[a,'teacher@example.org']);
  await as(teacher);
  await rpc('select pp_accept_invitations()');
  assert.equal((await rpc('select status from pp_memberships')).rows[0].status,'pending');
  assert.equal((await rpc('select * from pp_schools')).rows.length,0);
  assert.equal((await rpc('select * from pp_school_state')).rows.length,0);
  await assert.rejects(rpc('select pp_save_school($1,0,$2)',[a,{roster:{}}]),/SCHOOL_ACCESS_REQUIRED/);
  await assert.rejects(rpc("select pp_create_school('Stolen admin')"),/ADMIN_REQUIRED/);
  await assert.rejects(rpc("insert into pp_admins values ($1)",[teacher]),/permission denied/);
  const member=(await rpc('select id from pp_memberships')).rows[0].id;
  await assert.rejects(rpc("update pp_memberships set status='approved' where id=$1",[member]),/permission denied/);
  await assert.rejects(rpc("select pp_review_member($1,'approved')",[member]),/ADMIN_REQUIRED/);
  await as(admin);await rpc("select pp_review_member($1,'approved')",[member]);
  await as(teacher);
  assert.deepEqual((await rpc('select id from pp_schools')).rows.map(x=>x.id),[a]);
  assert.equal((await rpc('select * from pp_school_state where school_id=$1',[b])).rows.length,0);
  assert.equal((await rpc('select pp_save_school($1,0,$2) revision',[a,{roster:{},classes:{}}])).rows[0].revision,1);
  await assert.rejects(rpc('select pp_save_school($1,0,$2)',[a,{roster:{}}]),/SCHOOL_CONFLICT/);
  await assert.rejects(rpc('select pp_save_school($1,0,$2)',[b,{roster:{}}]),/SCHOOL_ACCESS_REQUIRED/);
  await assert.rejects(rpc('select pp_invite($1,$2)',[b,'outsider@example.org']),/SCHOOL_ACCESS_REQUIRED/);
  await as(outsider);assert.equal((await rpc('select * from pp_schools')).rows.length,0);
  assert.equal((await rpc('select * from pp_memberships')).rows.length,0);
  await as(admin);await rpc("select pp_review_member($1,'revoked')",[member]);
  await as(teacher);await rpc('select pp_accept_invitations()');
  assert.equal((await rpc('select status from pp_memberships')).rows[0].status,'revoked');
  assert.equal((await rpc('select * from pp_schools')).rows.length,0);
  await assert.rejects(rpc('select pp_save_school($1,1,$2)',[a,{}]),/SCHOOL_ACCESS_REQUIRED/);
  await db.exec('reset role;set role anon');
  await assert.rejects(rpc('select * from pp_schools'),/permission denied/);
  await assert.rejects(rpc("select pp_create_school('Anon school')"),/permission denied/);
 }finally{await db.close();}
});
