const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
test('family access projects only a linked child and grades quizzes on the server',async()=>{
 const db=new PGlite();
 const ids=Array.from({length:5},(_,i)=>'00000000-0000-0000-0000-'+String(i+1).padStart(12,'0'));
 const [admin,teacher,parent,student,outsider]=ids;
 try{
  await db.exec(`create role anon;create role authenticated;create schema auth;
   create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
  await db.exec(fs.readFileSync('supabase/schema.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/platform.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/platform.sql','utf8')); // Re-running is safe.
  for(let i=0;i<ids.length;i++)await db.query('insert into auth.users values ($1,$2,now())',[ids[i],['shafiphysika@gmail.com','teacher@example.org','parent@example.org','student@example.org','outsider@example.org'][i]]);
  const as=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
  const q=(sql,args=[])=>db.query(sql,args);
  await as(outsider);assert.equal((await q('select pp_claim_owner() claimed')).rows[0].claimed,false);
  await as(admin);assert.equal((await q('select pp_claim_owner() claimed')).rows[0].claimed,true);
  const school=(await q("select pp_create_school('Test school') id")).rows[0].id;
  const other=(await q("select pp_create_school('Other school') id")).rows[0].id;
  await q('select pp_invite($1,$2)',[school,'teacher@example.org']);
  await as(teacher);await q('select pp_accept_invitations()');const member=(await q('select id from pp_memberships')).rows[0].id;
  await as(admin);await q("select pp_review_member($1,'approved')",[member]);
  const data={roster:{'607':{names:['Alice','Bob']}},classes:{'607':{pts:{1:7,2:99},log:{1:[{g:'Reading',p:2}],2:[{g:'Private Bob'}]}}},portal:{lessons:[{id:'quiz',classId:'607',title:'Quiz',kind:'quiz',published:true,questions:[{prompt:'Hi?',choices:['Hello','Goodbye'],answer:0}]},{id:'draft',classId:'607',title:'Secret draft',published:false},{id:'hw',classId:'607',title:'Write',kind:'assignment',published:true},{id:'other',classId:'606',title:'Other class',published:true}],assessments:[{id:'read',classId:'607',maximum:20}],scores:{read:{1:{score:0,feedback:'Keep trying'},2:{score:20,feedback:'Bob private'}}},attendance:{'2026-10-08':{'607':{1:'late',2:'absent'}}},announcements:[{id:'n',classId:'607',title:'Welcome',body:'Class news'}]}};
  await q('select pp_save_school($1,0,$2)',[school,data]);
  await as(teacher);
  await q('select pp_invite_family($1,$2,$3,$4,$5)',[school,'607',1,'parent@example.org','parent']);
  await q('select pp_invite_family($1,$2,$3,$4,$5)',[school,'607',1,'student@example.org','student']);
  await assert.rejects(q('select pp_invite_family($1,$2,$3,$4,$5)',[other,'607',1,'parent@example.org','parent']),/SCHOOL_ACCESS_REQUIRED/);
  await as(parent);await q('select pp_accept_family()');
  const parentLink=(await q('select * from pp_family_links')).rows[0].id;
  assert.equal((await q('select * from pp_school_state')).rows.length,0);
  const feed=(await q('select pp_family_feed($1) data',[parentLink])).rows[0].data;
  assert.equal(feed.name,'Alice');assert.equal(feed.points,7);assert.equal(feed.lessons.length,2);
  assert.equal(feed.lessons[0].questions[0].answer,undefined);
  assert.equal(feed.assessments[0].grade.score,0);
  assert.equal(feed.attendance[0].status,'late');
  assert.equal(feed.history[0].g,'Reading');
  assert.ok(!JSON.stringify(feed).includes('Bob'));assert.ok(!JSON.stringify(feed).includes('Secret draft'));
  await assert.rejects(q('select pp_submit_work($1,$2,$3,$4)',[parentLink,'hw','Parent spoof',[]]),/STUDENT_REQUIRED/);
  await as(student);await q('select pp_accept_family()');const studentLink=(await q('select * from pp_family_links')).rows[0].id;
  await assert.rejects(q('select pp_family_feed($1)',[parentLink]),/LINK_REQUIRED/);
  await assert.rejects(q('select pp_submit_work($1,$2,$3,$4)',[studentLink,'draft','Secret',[]]),/LESSON_REQUIRED/);
  await assert.rejects(q('select pp_submit_work($1,$2,$3,$4)',[studentLink,'quiz','',[999]]),/INVALID_ANSWERS/);
  const result=(await q('select pp_submit_work($1,$2,$3,$4) data',[studentLink,'quiz','',[0]])).rows[0].data;
  assert.equal(result.score,1);assert.equal(result.maximum,1);
  await assert.rejects(q('select pp_submit_work($1,$2,$3,$4)',[studentLink,'quiz','',[1]]),/WORK_ALREADY_REVIEWED/);
  await q('select pp_submit_work($1,$2,$3,$4)',[studentLink,'hw','My work',[]]);
  await as(teacher);const submission=(await q("select id from pp_submissions where lesson_id='hw'")).rows[0].id;
  const changedRoster=structuredClone(data);changedRoster.roster['607'].names[0]='Different child';
  await assert.rejects(q('select pp_save_school($1,1,$2)',[school,changedRoster]),/ROSTER_LINKED/);
  await q('select pp_review_work($1,$2,$3,$4)',[submission,8,10,'Well done']);
  await as(outsider);assert.equal((await q('select * from pp_submissions')).rows.length,0);
  await assert.rejects(q('select pp_review_work($1,$2,$3,$4)',[submission,10,10,'Spoof']),/SCHOOL_ACCESS_REQUIRED/);
  await as(student);const graded=(await q('select pp_family_feed($1) data',[studentLink])).rows[0].data.submissions.find(s=>s.lesson_id==='hw');assert.equal(graded.score,8);
  await as(teacher);await q('select pp_revoke_family($1)',[studentLink]);
  await as(student);await assert.rejects(q('select pp_family_feed($1)',[studentLink]),/LINK_REQUIRED/);
  await as(teacher);await q('select pp_invite_family($1,$2,$3,$4,$5)',[school,'607',2,'outsider@example.org','parent']);
  const reassigned=structuredClone(data);reassigned.roster['607'].names[1]='New student';
  await q('select pp_save_school($1,1,$2)',[school,reassigned]);
  await as(outsider);await q('select pp_accept_family()');
  assert.equal((await q('select * from pp_family_links')).rows.length,0,'a stale invitation cannot inherit a reassigned seat');
  await assert.rejects(q('select * from pp_owner_bootstrap'),/permission denied/);
  await db.exec('reset role;set role anon');await assert.rejects(q('select pp_family_feed($1)',[parentLink]),/permission denied/);
 }finally{await db.close();}
});
