const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const PartyCore=require('../party-core.js');
const PortalCore=require('../portal-core.js');
const MaterialCore=require('../materials-core.js');
test('school permissions enforce every domain on the server and cannot be self-granted',async()=>{
 const db=new PGlite();const admin='00000000-0000-0000-0000-000000000001',teacher='00000000-0000-0000-0000-000000000002';
 try{
  await db.exec(`create role anon;create role authenticated;create schema auth;create schema storage;
   create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
   create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
   grant usage on schema auth,storage to authenticated;grant execute on function auth.uid() to authenticated;
   create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
   create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
   alter table storage.objects enable row level security;grant select,insert on storage.objects to authenticated;`);
  for(const name of ['schema','platform','materials','permissions'])await db.exec(fs.readFileSync('supabase/'+name+'.sql','utf8'));
  await db.exec(fs.readFileSync('supabase/permissions.sql','utf8'));
  await db.query('insert into auth.users values($1,$2,now()),($3,$4,now())',[admin,'shafiphysika@gmail.com',teacher,'teacher@example.org']);
  const as=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
  const q=(sql,args=[])=>db.query(sql,args);
  await as(admin);await q('select pp_claim_owner()');const school=(await q("select pp_create_school('A') id")).rows[0].id,other=(await q("select pp_create_school('B') id")).rows[0].id;
  let data={roster:{401:{teacher:'T',names:['Amy']}},classes:{401:PartyCore.sanitizeClass({})},portal:PortalCore.clean({}),materials:MaterialCore.clean({}),links:[]},revision=1;
  await q('select pp_save_school($1,0,$2)',[school,data]);await q('select pp_invite($1,$2)',[school,'teacher@example.org']);
  await as(teacher);await q('select pp_accept_invitations()');const member=(await q('select id from pp_memberships')).rows[0].id;
  assert.equal((await q("select pp_can_school($1,'points') allowed",[school])).rows[0].allowed,false);
  await as(admin);await q("select pp_review_member($1,'approved')",[member]);await as(teacher);
  assert.equal((await q("select pp_can_school($1,'points') allowed",[school])).rows[0].allowed,true);
  await assert.rejects(q('select pp_set_member_permissions($1,$2)',[member,{materials:true}]),/ADMIN_REQUIRED/);
  await assert.rejects(q("update pp_memberships set permissions='{}' where id=$1",[member]),/permission denied/);
  await db.exec('reset role');
  const link=(await q("insert into pp_family_links(school_id,class_id,seat,user_id,email,kind) values($1,'401',1,$2,'teacher@example.org','parent') returning id",[school,teacher])).rows[0].id;
  const submission=(await q("insert into pp_submissions(school_id,class_id,seat,lesson_id,user_id,body) values($1,'401',1,'lesson',$2,'A response') returning id",[school,teacher])).rows[0].id;
  await as(teacher);
  await assert.rejects(q('select pp_revoke_family($1)',[link]),/PERMISSION_INVITE_REQUIRED/);
  await assert.rejects(q("select pp_review_work($1,1,2,'Feedback')",[submission]),/PERMISSION_ACTIVITIES_REQUIRED/);
  const save=async(next)=>{const result=await q('select pp_save_school($1,$2,$3) revision',[school,revision,next]);revision=result.rows[0].revision;data=next;};
  const next=()=>structuredClone(data);
  // Opening the point board initializes its deterministic default teams.
  let changed=next();changed.classes[401].pts[1]=2;changed.classes[401].teams=[[1],[],[],[]];await save(changed);
  changed=next();changed.classes[401].pts[1]=4;changed.gameImportReceipts=['a'.repeat(64)];await save(changed);
  changed=next();changed.classes[401].teams=null;changed.classes[401].teamCount=1000000000;
  await assert.rejects(save(changed),/INVALID_SCHOOL_DATA/);
  changed=next();changed.classes[401].picked=[1];await assert.rejects(save(changed),/PERMISSION_ACTIVITIES_REQUIRED/);
  changed=next();changed.materials.plans=[{id:'plan',classId:'401',title:'Story'}];await assert.rejects(save(changed),/PERMISSION_MATERIALS_REQUIRED/);
  changed=next();changed.roster[401].names[0]='Other child';await assert.rejects(save(changed),/PERMISSION_ROSTER_REQUIRED/);
  changed=next();changed.portal.attendance={'2026-10-10':{401:{1:'absent'}}};await assert.rejects(save(changed),/PERMISSION_ROSTER_REQUIRED/);
  changed=next();changed.portal.lessons=[{id:'l',classId:'401',title:'Story'}];await assert.rejects(save(changed),/PERMISSION_ACTIVITIES_REQUIRED/);
  await assert.rejects(q('select pp_invite($1,$2)',[school,'other@example.org']),/PERMISSION_INVITE_REQUIRED/);
  const path=school+'/11111111-1111-1111-1111-111111111111/slides.pptx';
  await assert.rejects(q("insert into storage.objects(bucket_id,name) values('pp-materials',$1)",[path]),/row-level security/);
  await assert.rejects(q("select pp_invite_family($1,'401',1,'parent@example.org','parent')",[school]),/PERMISSION_INVITE_REQUIRED/);
  await assert.rejects(q('select pp_save_school($1,0,$2)',[other,{}]),/SCHOOL_ACCESS_REQUIRED/);
  await as(admin);
  await assert.rejects(q('select pp_set_member_permissions($1,$2)',[member,{materials:'true'}]),/INVALID_PERMISSIONS/);
  await assert.rejects(q('select pp_set_member_permissions($1,$2)',[member,{admin:true}]),/INVALID_PERMISSIONS/);
  await q('select pp_set_member_permissions($1,$2)',[member,{points:false,activities:true,materials:true,roster:false,invite:true}]);await as(teacher);
  changed=next();changed.classes[401].pts[1]=100;await assert.rejects(save(changed),/PERMISSION_POINTS_REQUIRED/);
  changed=next();changed.gameImportReceipts.push('b'.repeat(64));await assert.rejects(save(changed),/PERMISSION_POINTS_REQUIRED/);
  changed=next();changed.classes[401].picked=[1];changed.materials.plans=[{id:'plan',classId:'401',title:'Story'}];await save(changed);
  await q("insert into storage.objects(bucket_id,name) values('pp-materials',$1)",[path]);
  await q('select pp_invite($1,$2)',[school,'other@example.org']);
  await q('select pp_revoke_family($1)',[link]);
  await q("select pp_review_work($1,1,2,'Feedback')",[submission]);
  await assert.rejects(q('select pp_save_school($1,$2,$3)',[school,0,data]),/SCHOOL_CONFLICT/);
  changed=next();changed.classes[401].unexpected='bypass';await assert.rejects(save(changed),/PERMISSION_ROSTER_REQUIRED/);
  changed=next();changed.extraAdminFlag=true;await assert.rejects(save(changed),/PERMISSION_ROSTER_REQUIRED/);
  await as(admin);await q("select pp_review_member($1,'revoked')",[member]);await as(teacher);
  assert.equal((await q("select pp_can_school($1,'materials') allowed",[school])).rows[0].allowed,false);
  await assert.rejects(save(data),/SCHOOL_ACCESS_REQUIRED/);
 }finally{await db.close();}
});
